Chore: secure workflows (#461)
<!-- Thank you for concidering to create a pull request for this
project.

We utilise a bot to analyse the code quality of the pull request. Please
make sure that the bot is happy with your changes before submitting the
pull request.
As an additional benefit of this bot, we can automatically generate a
description for your pull request based on the commit messages.

We would still love you to explain what you have done in your own words,
but if you are in a hurry, you can just submit the pull request without
a description and the bot will generate one for you.

-->

<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

- **Chores**
- Enhanced SSH key setup and Git configuration across various workflows
for improved security and efficiency.
- Introduced Workflow Telemetry in multiple workflows for better
monitoring and data collection.
- Updated actions and configurations in workflows related to
development, security, and management to streamline operations and
enhance security measures.
- Adjusted NPM registry configurations for secure and efficient package
management.
- Reorganized steps and updated actions versions to improve workflow
efficiency and security.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->

---------

Signed-off-by: Jonathan Stevens <jonathan.stevens@eventiva.co.uk>

diff --git a/.github/workflows/chore-readme-fun.yml b/.github/workflows/chore-readme-fun.yml
--- a/.github/workflows/chore-readme-fun.yml
+++ b/.github/workflows/chore-readme-fun.yml
@@ -77,8 +77,45 @@ jobs:
         with:
           egress-policy: audit
 
-      - name: Checkout repo
-        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - name: Workflow Telemetry
+        uses: catchpoint/workflow-telemetry-action@6705383eabd01833acfe8412ec697384830e1455 # v1.8.7
+        with: 
+          github_token: ${{ secrets.BOT_TOKEN || github.token }}
+          comment_on_pr: false
+          theme: dark
+          proc_trace_sys_enable: true
+
+      # checks out the repository
+      - uses: actions/checkout@v4
+        with:
+          submodules: 'recursive'
+          token: "${{ secrets.BOT_TOKEN || github.token }}"
+
+      - name: Create SSH key
+        run: |
+          mkdir -p ~/.ssh/
+          echo "${{ secrets.BOT_GIT_SSH_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          chmod 644 ~/.ssh/known_hosts
+
+      # ensure git is using the ssh key
+      - name: Ensure git is using the SSH key
+        run: |
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/id_rsa
+          ssh-add -l | grep -q "$(ssh-keygen -lf ~/.ssh/id_rsa | awk '{print $2}')" || (echo "Failed to add SSH key" && exit 1)
+
+      # setup git to use the ssh key
+      - name: Setup git
+        run: |
+          git config --global user.name ${{secrets.GIT_USER_NAME}}
+          git config --global user.email ${{secrets.GIT_USER_EMAIL}}
+          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
+          git config --global user.signingkey ~/.ssh/id_rsa
+          git config --global commit.gpgsign true
+          git config --global tag.gpgsign true
+          
       # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
       - name: generate github-contribution-grid-snake.svg
         uses: Platane/snk/svg-only@8b7b3e6acef87188f941ed83b47f9da0401b4d17 # v3.2.0
diff --git a/.github/workflows/chore-trunk-nightly.yml b/.github/workflows/chore-trunk-nightly.yml
--- a/.github/workflows/chore-trunk-nightly.yml
+++ b/.github/workflows/chore-trunk-nightly.yml
@@ -59,10 +59,7 @@ jobs:
   trunk_upgrade:
     name: Upgrade Trunk
     runs-on: ubuntu-latest
-    env:
-      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
-      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
-      BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}
+    
     permissions:
       contents: write # For trunk to create PRs
       pull-requests: write # For trunk to create PRs
@@ -71,7 +68,7 @@ jobs:
         uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
         with:
           egress-policy: audit
-      
+
       - name: Workflow Telemetry
         uses: catchpoint/workflow-telemetry-action@6705383eabd01833acfe8412ec697384830e1455 # v1.8.7
         with: 
@@ -80,8 +77,36 @@ jobs:
           theme: dark
           proc_trace_sys_enable: true
 
-      - name: Checkout
-        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
+      # checks out the repository
+      - uses: actions/checkout@v4
+        with:
+          submodules: 'recursive'
+          token: "${{ secrets.BOT_TOKEN || github.token }}"
+
+      - name: Create SSH key
+        run: |
+          mkdir -p ~/.ssh/
+          echo "${{ secrets.BOT_GIT_SSH_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          chmod 644 ~/.ssh/known_hosts
+
+      # ensure git is using the ssh key
+      - name: Ensure git is using the SSH key
+        run: |
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/id_rsa
+          ssh-add -l | grep -q "$(ssh-keygen -lf ~/.ssh/id_rsa | awk '{print $2}')" || (echo "Failed to add SSH key" && exit 1)
+
+      # setup git to use the ssh key
+      - name: Setup git
+        run: |
+          git config --global user.name ${{secrets.GIT_USER_NAME}}
+          git config --global user.email ${{secrets.GIT_USER_EMAIL}}
+          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
+          git config --global user.signingkey ~/.ssh/id_rsa
+          git config --global commit.gpgsign true
+          git config --global tag.gpgsign true
 
       # >>> Install your own deps here (npm install, etc) <<<
       - name: Trunk Upgrade
@@ -93,10 +118,7 @@ jobs:
     permissions:
       checks: write # For trunk to post annotations
       contents: read # For repo checkout
-    env:
-      GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
-      GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
-      BIT_CONFIG_USER_TOKEN: ${{ secrets.BIT_CONFIG_USER_TOKEN }}
+    
       
     steps:
       - name: Harden Runner
@@ -115,14 +137,25 @@ jobs:
       - name: Checkout
         uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
 
-      - name: Initialize Bit
-        uses: bit-tasks/init@e2ce273c218d39dfc68925c80f6da33e16407c87 # v1
-      - name: Resolve component packages from bit.cloud registry (Mandatory for component installation using package managers other than Bit)
+      - name: Setup git & npm
+        run: |
+          git config --global user.name ${{secrets.GIT_USER_NAME}}
+          git config --global user.email ${{secrets.GIT_USER_EMAIL}}
+          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
+          git config --global user.signingkey ~/.ssh/id_rsa
+          git config --global commit.gpgsign true
+          git config --global tag.gpgsign true
+
+      - name: Setup NPM Registry
         run: |
           npm config set '@bit:registry' https://node-registry.bit.cloud
           npm config set '@teambit:registry' https://node-registry.bit.cloud
           npm config set '@eventiva:registry' https://node-registry.bit.cloud
-          npm config set //node-registry.bit.cloud/:_authToken ${{ env.BIT_CONFIG_USER_TOKEN }}
+          npm config set //node-registry.bit.cloud/:_authToken ${{ secrets.BIT_CONFIG_USER_TOKEN }}
+
+      - name: Initialize Bit
+        uses: bit-tasks/init@e2ce273c218d39dfc68925c80f6da33e16407c87 # v1
+
 
       - name: Trunk Check
         uses: trunk-io/trunk-action@97ecd21fe6c743bf7a606791584b683a7995c70e # v1.1.9
diff --git a/.github/workflows/security-scorecard.yml b/.github/workflows/security-scorecard.yml
--- a/.github/workflows/security-scorecard.yml
+++ b/.github/workflows/security-scorecard.yml
@@ -86,10 +86,51 @@ jobs:
         with:
           egress-policy: audit
 
-      - name: "Checkout code"
-        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
+      - name: Workflow Telemetry
+        uses: catchpoint/workflow-telemetry-action@6705383eabd01833acfe8412ec697384830e1455 # v1.8.7
+        with: 
+          github_token: ${{ secrets.BOT_TOKEN || github.token }}
+          comment_on_pr: false
+          theme: dark
+          proc_trace_sys_enable: true
+
+      # checks out the repository
+      - uses: actions/checkout@v4
         with:
-          persist-credentials: false
+          submodules: 'recursive'
+          token: "${{ secrets.BOT_TOKEN || github.token }}"
+
+      - name: Create SSH key
+        run: |
+          mkdir -p ~/.ssh/
+          echo "${{ secrets.BOT_GIT_SSH_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          chmod 644 ~/.ssh/known_hosts
+
+      # ensure git is using the ssh key
+      - name: Ensure git is using the SSH key
+        run: |
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/id_rsa
+          ssh-add -l | grep -q "$(ssh-keygen -lf ~/.ssh/id_rsa | awk '{print $2}')" || (echo "Failed to add SSH key" && exit 1)
+
+      # setup git to use the ssh key
+      - name: Setup git & npm
+        run: |
+          git config --global user.name ${{secrets.GIT_USER_NAME}}
+          git config --global user.email ${{secrets.GIT_USER_EMAIL}}
+          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
+          git config --global user.signingkey ~/.ssh/id_rsa
+          git config --global commit.gpgsign true
+          git config --global tag.gpgsign true
+
+      - name: Setup NPM Registry
+        run: |
+          npm config set '@bit:registry' https://node-registry.bit.cloud
+          npm config set '@teambit:registry' https://node-registry.bit.cloud
+          npm config set '@eventiva:registry' https://node-registry.bit.cloud
+          npm config set //node-registry.bit.cloud/:_authToken ${{ secrets.BIT_CONFIG_USER_TOKEN }}
 
       - name: "Run analysis"
         uses: ossf/scorecard-action@e38b1902ae4f44df626f11ba0734b14fb91f8f86 # v2.1.2
diff --git a/.github/workflows/security-secrets.yml b/.github/workflows/security-secrets.yml
--- a/.github/workflows/security-secrets.yml
+++ b/.github/workflows/security-secrets.yml
@@ -65,15 +65,49 @@ jobs:
       - name: Workflow Telemetry
         uses: catchpoint/workflow-telemetry-action@6705383eabd01833acfe8412ec697384830e1455 # v1.8.7
         with: 
+          github_token: ${{ secrets.BOT_TOKEN || github.token }}
           comment_on_pr: false
           theme: dark
           proc_trace_sys_enable: true
-      - name: Checkout
-        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
+
+      # checks out the repository
+      - uses: actions/checkout@v4
         with:
-          fetch-depth: 0 # fetch all history so multiple commits can be scanned
           submodules: 'recursive'
-          token: ${{ secrets.BOT_TOKEN || github.token }}
+          token: "${{ secrets.BOT_TOKEN || github.token }}"
+
+      - name: Create SSH key
+        run: |
+          mkdir -p ~/.ssh/
+          echo "${{ secrets.BOT_GIT_SSH_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          chmod 644 ~/.ssh/known_hosts
+
+      # ensure git is using the ssh key
+      - name: Ensure git is using the SSH key
+        run: |
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/id_rsa
+          ssh-add -l | grep -q "$(ssh-keygen -lf ~/.ssh/id_rsa | awk '{print $2}')" || (echo "Failed to add SSH key" && exit 1)
+
+      # setup git to use the ssh key
+      - name: Setup git & npm
+        run: |
+          git config --global user.name ${{secrets.GIT_USER_NAME}}
+          git config --global user.email ${{secrets.GIT_USER_EMAIL}}
+          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
+          git config --global user.signingkey ~/.ssh/id_rsa
+          git config --global commit.gpgsign true
+          git config --global tag.gpgsign true
+
+      - name: Setup NPM Registry
+        run: |
+          npm config set '@bit:registry' https://node-registry.bit.cloud
+          npm config set '@teambit:registry' https://node-registry.bit.cloud
+          npm config set '@eventiva:registry' https://node-registry.bit.cloud
+          npm config set //node-registry.bit.cloud/:_authToken ${{ secrets.BIT_CONFIG_USER_TOKEN }}
+
       - name: GitGuardian scan
         uses: GitGuardian/ggshield/actions/secret@5a6f8a571defbaf3375993f0091799a9afdf5c20 # main
         env:
