Chore: secure workflows (#461)
<!-- Thank you for concidering to create a pull request for this
project.

We utilise a bot to analyse the code quality of the pull request. Please
make sure that the bot is happy with your changes before submitting the
pull request.
As an additional benefit of this bot, we can automatically generate a
description for your pull request based on the commit messages.

We would still love you to explain what you have done in your own words,
but if you are in a hurry, you can just submit the pull request without
a description and the bot will generate one for you.

-->

<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

- **Chores**
- Enhanced SSH key setup and Git configuration across various workflows
for improved security and efficiency.
- Introduced Workflow Telemetry in multiple workflows for better
monitoring and data collection.
- Updated actions and configurations in workflows related to
development, security, and management to streamline operations and
enhance security measures.
- Adjusted NPM registry configurations for secure and efficient package
management.
- Reorganized steps and updated actions versions to improve workflow
efficiency and security.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->

---------

Signed-off-by: Jonathan Stevens <jonathan.stevens@eventiva.co.uk>

diff --git a/.github/workflows/chore-create-diagram.yml b/.github/workflows/chore-create-diagram.yml
--- a/.github/workflows/chore-create-diagram.yml
+++ b/.github/workflows/chore-create-diagram.yml
@@ -79,11 +79,39 @@ jobs:
           comment_on_pr: false
           theme: dark
           proc_trace_sys_enable: true
-      - name: Checkout code
-        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
+
+      # checks out the repository
+      - uses: actions/checkout@v4
         with:
           submodules: 'recursive'
           token: "${{ secrets.BOT_TOKEN || github.token }}"
+
+      - name: Create SSH key
+        run: |
+          mkdir -p ~/.ssh/
+          echo "${{ secrets.BOT_GIT_SSH_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          chmod 644 ~/.ssh/known_hosts
+
+      # ensure git is using the ssh key
+      - name: Ensure git is using the SSH key
+        run: |
+          eval "$(ssh-agent -s)"
+          ssh-add ~/.ssh/id_rsa
+          ssh-add -l | grep -q "$(ssh-keygen -lf ~/.ssh/id_rsa | awk '{print $2}')" || (echo "Failed to add SSH key" && exit 1)
+
+      # setup git to use the ssh key
+      - name: Setup git
+        run: |
+          git config --global user.name ${{secrets.GIT_USER_NAME}}
+          git config --global user.email ${{secrets.GIT_USER_EMAIL}}
+          git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
+          git config --global gpg.format ssh
+          git config --global user.signingkey ~/.ssh/id_rsa
+          git config --global commit.gpgsign true
+          git config --global tag.gpgsign true
+
       - name: Update diagram
         uses: githubocto/repo-visualizer@a999615bdab757559bf94bda1fe6eef232765f85 # main
         with:
