chore: update git configuration to use correct user name and email for Eventiva 🔧 chore(subrepo-pull.yml): add SSH key setup to ensure git is using the correct key for authentication 🔧 chore(subrepo-pull.yml): update git subrepo pull command to specify the develop branch 🔧 chore(subrepo-push.yml): update git configuration to use correct user name and email for Eventiva 🔧 chore(subrepo-push.yml): add SSH key setup to ensure git is using the correct key for authentication

diff --git a/.github/workflows/subrepo-push.yml b/.github/workflows/subrepo-push.yml
--- a/.github/workflows/subrepo-push.yml
+++ b/.github/workflows/subrepo-push.yml
@@ -2,8 +2,8 @@
  # @format
  # -----
  # Project: @eventiva/eventiva
- # File: subrepo.yml
- # Path: \.github\workflows\subrepo.yml
+ # File: subrepo-push.yml
+ # Path: \.github\workflows\subrepo-push.yml
  # Created Date: Wednesday, December 20th 2023
  # Author: Jonathan Stevens (Email: jonathan.stevens@eventiva.co.uk, Github: https://github.com/TGTGamer)
  # -----
@@ -48,11 +48,28 @@ jobs:
       with:
         path: 'eventiva'
 
-    - name: setup git configuration
-      working-directory: eventiva
+    # create the ssh key from the secrets
+    - name: Create SSH key
       run: |
-        git config user.name github-actions
-        git config user.email github-actions@github.com
+        mkdir -p ~/.ssh/
+        echo "${{ secrets.BOT_GIT_SSH_KEY }}" > ~/.ssh/id_rsa
+        chmod 600 ~/.ssh/id_rsa
+        ssh-keyscan github.com >> ~/.ssh/known_hosts
+        chmod 644 ~/.ssh/known_hosts
+
+    # ensure git is using the ssh key
+    - name: Ensure git is using the SSH key
+      run: |
+        eval "$(ssh-agent -s)"
+        ssh-add ~/.ssh/id_rsa
+        ssh-add -l | grep -q "$(ssh-keygen -lf ~/.ssh/id_rsa | awk '{print $2}')" || (echo "Failed to add SSH key" && exit 1)
+
+    # setup git to use the ssh key
+    - name: Setup git
+      run: |
+        git config --global user.name "Eventiva"
+        git config --global user.email "github@eventiva.co.uk"
+        git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=~/.ssh/known_hosts"
     
     - name: Update subrepo
       working-directory: eventiva
